### ISSUE TITLE
Just saying

### ISSUE THREAD

**Issue by shubhamjangid** [DataByteNITT/github-python-ks#1]
Why not install anaconda and finish it off!
It is recommended by most of the DataScientist and ML experts.

**Comment by kunparekh18** [comment]
Installing that monstrously-sized 480MB package is going to be a waste for the purpose of this KS where just 2 libraries are going to be elaborated upon. The miniconda system should be ideal as you can install packages at your discretion. 

I'd like to suggest we use Python 3+ as both ```matplotlib``` and ```numpy``` are supported on it, and most of the world including the Data Science community is shifting towards it.

**Comment by codexetreme** [comment]
@shubhamjangid , @kunparekh18  , I will be giving instructions to install anaconda when we meet, and we will install the python3 version of anaconda.

**Comment by codexetreme** [comment]
also as @kunparekh18 pointed out the package is huge, so we will be distributing copies.

**Comment by Jeet1994** [comment]
**[OFF TOPIC]**
Just a small idea, I believe, for the people who are beginning with coding in Python for Data Science; using **WinPython** would be much much better than using Anaconda. _WinPython gives you a separate folder with all the tools (including Ipython console and Spyder), you code inside that folder_. And, in case you screw up something while installing some dubious package, you can always delete the contents of the folder (leaving behind the code) and re-install it;  it will be good as new :bowtie: .
